### ISSUE TITLE
gpt-4o-mini Error: Unknown model at getEncodingNameForModel

### ISSUE THREAD

**Issue by 0xinhua** [dqbd/tiktoken#114]
Hi, when I used the latest model `gpt-4o-mini`, there was an error when I calculated the token size. I want to know if it is because js-tiktoken does not support new model gpt-4o-mini? many thanks.

the code:

```js

// model is gpt-4o-mini
  try {
    const enc = encodingForModel(model);  // js-tiktoken 
    promptTokens = messages.reduce(
      (total: number, msg: Message) => total + enc.encode(msg.content ?? '').length,
      0,
    )
  } catch (error) {
    console.log('tiktoken error', error)
    // Unknown model at getEncodingNameForModel
  }

```

**Comment by dqbd** [comment]
Solved by #112, please upgrade to newest version of js-tiktoken to get the correct types!
