### ISSUE TITLE
request for npm gpt-3.5-turbo support

### ISSUE THREAD

**Issue by temberature** [dqbd/tiktoken#17]
I found that there is already a gpt-3.5-turbo branch, but it is not released to https://www.npmjs.com, I would like to ask about when it will be released?

BTW. Thanks for your great work.

**Comment by dqbd** [comment]
Still working to brush out the breaking changes due to bundling stuff, but in the meantime, either:

1. Use `get_encoding("cl100k_base")`, which should correspond to `gpt-3.5-turbo` 
1. check out the `1.0.0-alpha.3` version, which should add support for `encoding_for_model("gpt-3.5-turbo")`

**Comment by temberature** [comment]
I attempted using the first cl100k_base, and it appears to yield the same outcome as reported in https://github.com/openai/tiktoken/issues/45.

Thank you for your kind reply~

**Comment by dqbd** [comment]
Version `1.0.0` has been published, which should add the support for `gpt-3.5-turbo`, `gpt-4` and `gpt-4-32k` models. LMK if the issue presists.
