### ISSUE TITLE
Will there be support for React?

### ISSUE THREAD

**Issue by Hayakii** [dqbd/tiktoken#19]
Will there be support for React? It doesn't seem possible on the tiktoken@1.0.0-alpha.3 version. Or maybe I don't understand how to use it? I'm not very familiar with coding, I'm doing a small project to improve myself

**Comment by dqbd** [comment]
Hello, React should be supported, but most likely you need to configure your bundler to support WASM ESM proposal. 

@Hayakii May I ask what are you using to bundle your React app (Vite, CRA, Next.js)?

**Comment by dqbd** [comment]
As far as you are using Vite or Next.js, the support should be there with appropriate code changes.

For CRA, please follow progress at #21
