### ISSUE TITLE
Create React App: Unhandled Rejection (TypeError): wasm.__wbindgen_add_to_stack_pointer is not a function

### ISSUE THREAD

**Issue by xiaohuoni** [dqbd/tiktoken#21]
![image](https://user-images.githubusercontent.com/11746742/225871612-b6541de4-dced-43c8-86d5-8920e691c805.png)

use webpack 5 

```
asyncWebAssembly: true,
      layers: true,
      topLevelAwait: true,

```

**Comment by nnmrts** [comment]
Please reopen this, still an issue.

**Comment by dqbd** [comment]
As far as I understand, the issue is contained within Create React App, is that the case @nnmrts?

**Comment by dqbd** [comment]
@nnmrts  Please follow these instructions to enable WASM support in CRA via @craco/craco:

https://github.com/dqbd/tiktoken/tree/main/js#create-react-app

**Comment by nnmrts** [comment]
> As far as I understand, the issue is contained within Create React App, is that the case @nnmrts?

@dqbd No, I have this exact problem when using the chatgpt module through https://esm.sh/chatgpt with Deno, not using CRA at all. :/

I can provide more details later, but yeah, this is not just an issue with CRA.

**Comment by nnmrts** [comment]
> As far as I understand, the issue is contained within Create React App, is that the case @nnmrts?

@dqbd No, I have this exact problem when using the chatgpt module through https://esm.sh/chatgpt with Deno, not using CRA at all. :/

I can provide more details later, but yeah, this is not just an issue with CRA.

**Comment by dqbd** [comment]
For Deno, please see #22
