### ISSUE TITLE
Expose "allowed special tokens" on encode API to typescript

### ISSUE THREAD

**Issue by darknoon** [dqbd/tiktoken#3]
We should to expose the special tokens to JS when encoding, like with [python](https://github.com/openai/tiktoken/blob/7830ed537badecefb5a357448be722bfd58f9fca/tiktoken/core.py#LL70C16-L70).
For example you might want your special part of a prompt to be able to use certain tokens but not user-generated content, so it needs to be a parameter.

```py
[enc.decode([t]) for t in enc.encode('<|im_start|>… <|im_end|> ', allowed_special={'<|im_end|>', '<|im_start|>'})]
```

**Comment by dqbd** [comment]
Should be resolved with the newest 0.4.0 version 😃
