### ISSUE TITLE
[Error] Unexpected character '' (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by jorge-vnarvaez** [dqbd/tiktoken#31]
Hi there, i'm currently using chatgpt package from npm. The problem is when i try to import chagpt package into vue or js files this error appears on my console. Following this, the following detail appears

[Error] Unexpected character '' (Note that you need plugins to import files that are not JavaScript)

C:\Users\Jorge\Desktop\interfaces\gpt_suggestions\node_modules\@dqbd\tiktoken\tiktoken_bg.wasm:1:0
1: asm☺☺�☻&`♥⌂⌂⌂☺⌂`☻⌂⌂☺⌂`☻⌂⌂`☺⌂`♥⌂⌂⌂`♦⌂⌂⌂⌂`☺⌂☺⌂`♠⌂⌂⌂⌂⌂⌂`♣⌂⌂⌂⌂⌂`♥⌂⌂⌂☺~`♦⌂⌂⌂⌂☺⌂`♣⌂⌂⌂⌂⌂☺⌂`⌂⌂⌂⌂⌂⌂⌂``☺⌂☺~`♠⌂⌂⌂⌂⌂⌂☺⌂`♦~~⌂⌂☺~`♣⌂⌂⌂~⌂`⌂⌂⌂⌂⌂⌂⌂☺⌂`☻⌂⌂☺~`☺⌂`☻⌂~☺⌂`
   ^
2: ⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂☺⌂`        ⌂⌂⌂⌂⌂⌂~~~`♥~⌂⌂☺⌂`♥⌂⌂~`♦⌂⌂⌂~`‼⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂☺⌂`☼⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂☺⌂`♂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂⌂☺⌂`   ⌂⌂⌂⌂⌂⌂⌂⌂⌂`♣⌂⌂|⌂⌂`♦⌂|⌂⌂`♣⌂⌂~⌂⌂`♦⌂~⌂⌂`♣⌂⌂}⌂⌂`♦⌂}⌂⌂`☻⌂~☻�☻►./tiktoken_bg.js→__wbindgen_object_drop_ref♥►./tiktoken_bg.js↨__wbindgen_is_undefined♠►./tiktoken_bg.js __wbg_stringify_029a979dfb73aa17♠►./tiktoken_bg.js§__wbindgen_string_get☻►./tiktoken_bg.js¶__wbindgen_error_new☺►./tiktoken_bg.js∟__wbg_parse_3ac95b51fc312db8☺►./tiktoken_bg.js►__wbindgen_throw☻♥�♠�♣♦♦☻♦▬♣♦♠♣☻♣☻♦♦☻♦♣♣♥☻♦3: ♦

I googled the error and read a lot of blogs but can't find a solution to this problem. Any ideas what is happening or how can i solve this?

**Comment by dqbd** [comment]
Hello @jorge-vnarvaez!

Sorry for the delay. In the case of Vue, assuming you are using Vite, have you tried changing the config: https://github.com/dqbd/tiktoken/tree/main/js#vite? 

If you are not using Vite, may I ask for the contents of `package.json`? A reproducible example would be the best 👍

**Comment by jorge-vnarvaez** [comment]
Hi, thanks for your response.

I maked a reproducible example in this code sandbox

https://codesandbox.io/embed/competent-varahamihira-5vn0ew?fontsize=14&hidenavigation=1&theme=dark

**Comment by dqbd** [comment]
I see, will look into `vue-cli`, but at the moment, consider using `vite` instead.

**Comment by dqbd** [comment]
To broaden support for non-WASM supported environments, consider using `js-tiktoken`, which is a pure JS port of `tiktoken`
