### ISSUE TITLE
How to import in nodejs server?

### ISSUE THREAD

**Issue by djaffer** [dqbd/tiktoken#32]
/node_modules/@dqbd/tiktoken/lite/tiktoken_bg.cjs:375
    throw new Error(getStringFromWasm0(arg0, arg1));
          ^

Error: null pointer passed to rust
    at module.exports.__wbindgen_throw (/node_modules/@dqbd/tiktoken/lite/tiktoken_bg.cjs:375:11)
    at wasm://wasm/0030beca:wasm-function[788]:0x70f59
    at wasm://wasm/0030beca:wasm-function[786]:0x70f3f
    at wasm://wasm/0030beca:wasm-function[654]:0x6bdba
    at wasm://wasm/0030beca:wasm-function[147]:0x477e2
    at Tiktoken.encode (/node_modules/@dqbd/tiktoken/lite/tiktoken_bg.cjs:223:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0

**Comment by djaffer** [comment]
nevermind use this package. You guys should clearly write that this will not work with nodejs without module support making it pointless for backend.

**Comment by dqbd** [comment]
> it gave rust null pointer error Uncaught (in promise) Error: null pointer passed to rust

Could you please share a reproducible example? Thanks

**Comment by bosunolanrewaju** [comment]
I encountered this same error when I try to encode a string after the encoding has been freed.
```js
const { get_encoding } = require("@dqbd/tiktoken");
const encoding = get_encoding("gpt2");
const tokens = encoding.encode("noone is there");
encoding.free();
const otherTokens = encoding.encode("second encoding"); // <-- this throws Error: null pointer passed to rust
```

**Comment by dqbd** [comment]
Multiple initialisation is definitely fine, as seen in your first example. However, in the second example, the encoder is being free'd and then accessed after freeing, which is invalid.

**Comment by djaffer** [comment]
Thanks. Why is free not automated by refactoring.
