### ISSUE TITLE
[BUG] library works in test, but fails in dev server

### ISSUE THREAD

**Issue by dhruv-anand-aintech** [dqbd/tiktoken#55]
I get this error when trying to run my typescript server with yarn dev, and sending a request to it:
```
✖ LinkError: WebAssembly.Instance(): Import #2 module="./tiktoken_bg.js" function="__wbg_stringify_029a979dfb73aa17" error: function import requires a callable
      at ../../tiktoken/tiktoken.cjs 
```

**Comment by dqbd** [comment]
Hello @dhruv-anand-aintech!

This does seem like the WASM import is mangled, would it be possible to share a reproducible example?
