### ISSUE TITLE
Plans for `gpt-3.5-turbo-16k`?

### ISSUE THREAD

**Issue by khill-fbmc** [dqbd/tiktoken#59]
I would try to submit a PR, but have no idea how the library works.

**Comment by beatrizdemiguelperez** [comment]
Hello! we are also looking forward tfor this version. @dqbd  Do you know when it will be supported???

**Comment by nikwen** [comment]
I'd assume the tokenizer is the same as for `gpt-3.5-turbo`.

**Comment by vlrevolution** [comment]
Yeah actually it is

**Comment by dqbd** [comment]
Hello! Both the `js-tiktoken@1.0.7` version and `tiktoken@1.0.10` version should have support for `gpt-3.5-turbo-16k` already! Let me know, if it's not working properly.

**Comment by merlindru** [comment]
For anyone coming here, please make sure to use the [**tiktoken**](https://www.npmjs.com/package/tiktoken) library, **not @dqbd/tiktoken**, which isn't being updated anymore

Could we put up a warning on the NPM page of @dqbd/tiktoken?
