### ISSUE TITLE
no such file or directory,_tiktoken_bg.wasm

### ISSUE THREAD

**Issue by kiraraty** [dqbd/tiktoken#60]
Activating extension 'YaleHuang.chatgpt-ai' failed: ENOENT: no such file or directory, open 'c:\Users\kirara\Desktop\chatgpt-vscode\dist\_tiktoken_bg.wasm'.

**Comment by dqbd** [comment]
Hi @kiraraty! 

Would it be possible to share a code snippet or a reproducible example? If not, consider using `js-tiktoken` if needed
