### ISSUE TITLE
NPMJS repository versions are out of date

### ISSUE THREAD

**Issue by kjvenalainen** [dqbd/tiktoken#63]
The last release at https://www.npmjs.com/package/@dqbd/tiktoken is 1.0.7.

However, in this repo the latest is 1.0.10.

Do you plan to release new versions via NPM repo?

**Comment by SvenSchoene** [comment]
This npm project is by the same maintainer is correctly set to 1.0.10: https://www.npmjs.com/package/tiktoken

It seems the deployment has changed.

![image](https://github.com/dqbd/tiktoken/assets/7631673/692cbede-56b6-4b8c-92ff-1bfba4d68749)

**Comment by dqbd** [comment]
Hello!
I've managed to obtain the `tiktoken` NPM package name and haven't dealt with`@dqbd/tiktoken` yet. Not sure, whether it is better to keep both packages up to date or mark `@dqbd/tiktoken` as deprecated yet, but will hopefully soon resolve the issue.
