### ISSUE TITLE
Exports file path is not found

### ISSUE THREAD

**Issue by aliuq** [dqbd/tiktoken#7]
The `exports` path is defined in package.json, but the `.mjs` file is missing from the dist directory.

https://github.com/dqbd/tiktoken/blob/main/js/package.json#L21

![image](https://user-images.githubusercontent.com/11707934/222874767-0c42cf23-df5c-4b00-81fb-05b87c00cd66.png)

**Comment by dqbd** [comment]
Good catch 👍 Will resolve the issue in #12
