### ISSUE TITLE
gpt-3.5-turbo-instruct support

### ISSUE THREAD

**Issue by danny-avila** [dqbd/tiktoken#73]
for now, I'm using text-davinci-003 for model encoding, but not sure if that's right with this new model series

**Comment by darknoon** [comment]
I think it's the newer `cl100k_base` not the older model type

**Comment by sam-goodwin** [comment]
> I think it's the newer cl100k_base not the older model type

Which model would that be?

Is this right?

```ts
encodingForModel("gpt-3.5-turbo");
```
