### ISSUE TITLE
missing TiktokenModel for version 3.5-turbo-16k 

### ISSUE THREAD

**Issue by hannahlaek-wt** [dqbd/tiktoken#74]
missing TiktokenModel for version 3.5-turbo-16k

**Comment by dqbd** [comment]
Hey @hannahlaek-wt!

Thanks for flagging! Will add the missing model, but for now consider using `cl100k_base` directly.

**Comment by Tanakpek** [comment]
what would be the closest to 3.5 turbo instruct?
