### ISSUE TITLE
Plans for gpt-4-turbo variants?

### ISSUE THREAD

**Issue by ianschmitz** [dqbd/tiktoken#80]
`gpt-4-1106-preview` and `gpt-4-1106-vision-preview` were recently added which are the new gpt-4-turbo models. Are there plans to incorporate this? Specifically into `js-tiktoken`?

**Comment by kamalkech** [comment]
Same question here!

**Comment by landermedia** [comment]
Following on this. Thanks

**Comment by ianschmitz** [comment]
Looks like this was released in `1.0.8`.
