### ISSUE TITLE
Add `gpt-4-turbo-preview` to `TiktokenModel`

### ISSUE THREAD

**Issue by huytool157** [dqbd/tiktoken#85]
https://openai.com/blog/new-embedding-models-and-api-updates

**Comment by mystist** [comment]
Please update ASAP, we are blocking at this moment🙏

**Comment by risu729** [comment]
resolved in #86

**Comment by dqbd** [comment]
Should be resolved in js-tiktoken@1.0.9 and tiktoken@1.0.12, thanks again @risu729 🙂
