### ISSUE TITLE
An error occurred during the deployment of the Vercel edge function

### ISSUE THREAD

**Issue by bowencool** [dqbd/tiktoken#93]
```
Error: The Edge Function "api/xx" is referencing unsupported modules:
--
 - __vc__ns__/0/api/stream-openai.js: js-tiktoken
```
<img width="953" alt="image" src="https://github.com/dqbd/tiktoken/assets/20217146/fc959dbe-85d7-4ba7-8e59-21f6b8ccf749">

**Comment by enricoros** [comment]
Works well here, can you describe your use cae more?

**Comment by dqbd** [comment]
Hello @bowencool! Does this issue still occur? There was a regression on Vercel side in the past, which prevented new deployments of non-NextJS routes. 

Feel free to reopen if the issue still occurs, will close for now!
